begin;
create extension if not exists pgtap with schema extensions;
select plan(20);
select ok(public.validate_discipline_timing_patch('{"options":{"invitationRule":["start-6d","start-3d"],"reminderRules":["deadline-2h"],"duration":["PT90M"]}}'), 'Choice lists accept internal values');
select ok(public.validate_discipline_timing_patch('{"options":{"invitationRule":null}}'), 'Field null inherits options');
select ok(public.validate_discipline_timing_patch('{"options":null,"reminderRules":[]}'), 'Options inherit while reminders are disabled');
select ok(not public.validate_discipline_timing_patch('{"options":{"unknown":["start"]}}'), 'Unknown option field rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":[]}}'), 'Empty list rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":["start","start"]}}'), 'Duplicates rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":["deadline-1d"]}}'), 'Wrong invitation anchor rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"reminderRules":["start-1h"]}}'), 'Wrong reminder anchor rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"duration":["PT0M"]}}'), 'Invalid duration rejected');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":[null]}}'), 'Nonstring option rejected');
select ok(not public.validate_discipline_timing_patch(jsonb_build_object('options',jsonb_build_object('invitationRule',(select jsonb_agg('start-'||n||'h') from generate_series(1,33) n)))), 'List capped at 32');
select ok(public.validate_discipline_timing_patch('{"invitationRule":"start-6d","options":{"invitationRule":["start-1d"]}}'), 'Existing defaults may lie outside the choices');
select hasnt_table('public','activity_defaults','Old defaults table removed; discipline options are code-owned');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":["start"]}}'), 'Invitation at start is impossible');
select ok(not public.validate_discipline_timing_patch('{"options":{"invitationRule":["start-0d-0h"]}}'), 'Zero invitation offsets are impossible');
select ok(not public.validate_discipline_timing_patch('{"options":{"reminderRules":["deadline"]}}'), 'Reminder at deadline is impossible');
select ok(not public.validate_discipline_timing_patch('{"options":{"reminderRules":["deadline-0m"]}}'), 'Zero reminder offset is impossible');
select ok(public.validate_discipline_timing_patch('{"options":{"invitationRule":["start/d"],"reminderRules":["deadline/d"]}}'), 'Day-start choices can precede their anchor');
select ok(public.validate_discipline_timing_patch('{"options":{"responseDueRule":["start"],"gatheringRule":["start-0m"]}}'), 'Zero offsets allowed for response and gathering');
select ok(public.validate_discipline_timing_patch('{"invitationRule":"start","reminderRules":["deadline"]}'), 'Legacy selected defaults retain syntax validation');
select * from finish();
rollback;
