begin;
create extension if not exists pgtap with schema extensions;
select plan(13);
select ok(public.validate_activity_defaults_patch('{"options":{"invitationRule":["start-6d","start-3d"],"reminderRules":["deadline-2h"],"duration":["PT90M"]}}'), 'Choice lists accept internal values');
select ok(public.validate_activity_defaults_patch('{"options":{"invitationRule":null}}'), 'Field null inherits options');
select ok(public.validate_activity_defaults_patch('{"options":null,"reminderRules":[]}'), 'Options inherit while reminders are disabled');
select ok(not public.validate_activity_defaults_patch('{"options":{"unknown":["start"]}}'), 'Unknown option field rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"invitationRule":[]}}'), 'Empty list rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"invitationRule":["start","start"]}}'), 'Duplicates rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"invitationRule":["deadline-1d"]}}'), 'Wrong invitation anchor rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"reminderRules":["start-1h"]}}'), 'Wrong reminder anchor rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"duration":["PT0M"]}}'), 'Invalid duration rejected');
select ok(not public.validate_activity_defaults_patch('{"options":{"invitationRule":[null]}}'), 'Nonstring option rejected');
select ok(not public.validate_activity_defaults_patch(jsonb_build_object('options',jsonb_build_object('invitationRule',(select jsonb_agg('start-'||n||'h') from generate_series(1,33) n)))), 'List capped at 32');
select ok(public.validate_activity_defaults_patch('{"invitationRule":"start-6d","options":{"invitationRule":["start-1d"]}}'), 'Existing defaults may lie outside the choices');
select ok(not exists(select 1 from public.activity_types t where t.organization_id is null and not exists(select 1 from public.activity_defaults d where d.activity_type_id=t.id and d.scope='system' and d.values ? 'options')), 'System choice lists seeded for shared types');
select * from finish();
rollback;
